# Generated by Django 2.2.5 on 2019-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(verbose_name='idade'),
        ),
    ]
